// @input  -- the item types one sampled page of results carried
// @output -- evidence records for the result-shape checks (9.1, 9.4)
// @pos    -- pure projection; owns no credential, makes no request
// 一旦本文件被更新，务必更新开头注释及所属文件夹的 _DIR.md

import type { SeoAuditRecord } from "./types.ts";

/**
 * The provider's own item-type names for an AI answer block.
 *
 * Two of them because the provider has renamed this surface once already, and a
 * list that only knows the old name reports "no AI answer" on every page that
 * has the new one.
 */
const AI_ANSWER_ITEM_TYPES: readonly string[] = [
  "ai_overview",
  "ai_overview_reference",
];

/**
 * Item types that are somebody else's readers answering the question.
 *
 * Forums, video and social posts are the surfaces where a result is a person
 * rather than a publisher. Their presence says the query has an audience that
 * wants discussion, which is a different opportunity from a page that ranks.
 *
 * `people_also_ask` is deliberately not one of them: those questions are
 * generated by the search engine, not written by readers, and counting them
 * would make almost every query look like it has a community — which passes the
 * check by widening it rather than by measuring it.
 */
const COMMUNITY_ITEM_TYPES: readonly string[] = [
  "discussions_and_forums",
  "forum",
  "video",
  "twitter",
];

/**
 * The landscape region this projects, narrowed to what these checks read.
 *
 * Structural rather than an import: this package must not depend on the app's
 * wire contract, and the two fields below are the whole of what 9.1 and 9.4
 * need from it. The sample itself is taken once by the On-Page Checker's paid
 * lookup — these checks add no call of their own.
 */
export interface SerpShapeRaw {
  /** The query the page was sampled for, as the visitor confirmed it. */
  readonly keyword: string;
  /**
   * Item types the provider reported, or null when it reported none.
   *
   * Null is not "the page had none". The provider omits the block rather than
   * sending an empty list, so reading null as absence turns a gap in the
   * response into a finding about the results page.
   */
  readonly itemTypes: readonly string[] | null;
  /** Organic items dropped as unusable, so a thin sample is visible. */
  readonly unresolvedItemCount: number;
  /** How many organic results the sample actually contains. */
  readonly organicCount: number;
  /**
   * Estimated monthly organic traffic per page-one domain, when measured.
   *
   * Null means the market has no legal Labs pair, or the lookup did not
   * answer. Never an empty list in that case: an empty list reads as "page one
   * has no low-traffic site", which is a finding, and manufacturing it from a
   * provider gap is the opposite of what 9.3 is for.
   */
  readonly domainTraffic:
    | readonly { readonly domain: string; readonly organicEtv: number | null }[]
    | null;
  readonly marketCode: string;
  readonly languageCode: string;
}

/**
 * Why there is no sample, when there is none.
 *
 * The first version had one sentence for all of them — "no target query was
 * confirmed" — which the handler could only ever emit AFTER a query had been
 * confirmed, so it was false in every state that could show it and it hid the
 * three causes worth acting on.
 */
export type SerpShapeGap =
  | "no_confirmed_query"
  | "source_not_configured"
  | "market_not_supported"
  | "provider_unavailable";

const GAP_LIMITATION: Readonly<Record<SerpShapeGap, string>> = {
  no_confirmed_query:
    "no_target_query_was_confirmed_so_no_results_page_was_sampled",
  source_not_configured:
    "no_results_page_provider_was_configured_for_this_run",
  market_not_supported:
    "this_runs_market_is_not_one_the_results_page_provider_covers",
  provider_unavailable:
    "the_results_page_provider_did_not_answer_this_run",
};

function shapeRecord(
  id: string,
  raw: SerpShapeRaw | null | undefined,
  gap: SerpShapeGap,
  present: (types: readonly string[]) => readonly string[],
  presentLabel: string,
  /** Whether finding the shape is the problem (9.1) or missing it is (9.4). */
  affectedWhen: "present" | "absent",
): SeoAuditRecord {
  const unmeasured = (limitation: string): SeoAuditRecord => ({
    id,
    category: "serp_shape",
    state: "unverified",
    unit: "pages",
    // About the page that was submitted, for the query it targets. The page
    // projection narrows site-wide records to one page and has nothing to
    // narrow here; under any other population its site-level observation is
    // dropped and both checks come back "not tested" on every run.
    population: "target_page",
    // Counts a results page rather than the site's pages, so membership of the
    // crawled population is not a question this record answers.
    targetTested: null,
    tested: 0,
    affected: 0,
    observations: [],
    limitation,
  });

  if (!raw) return unmeasured(GAP_LIMITATION[gap]);
  if (raw.itemTypes === null) {
    // The whole check is about which blocks the page carried. Without that list
    // there is nothing to read, and reading its absence as "no blocks" would
    // report every unlisted page as clean.
    return unmeasured(
      "the_provider_reported_no_item_type_list_for_this_results_page",
    );
  }

  const matched = present(raw.itemTypes);
  const affected = affectedWhen === "present" ? matched.length > 0 : matched.length === 0;
  return {
    id,
    category: "serp_shape",
    state: affected ? "observed" : "not_observed",
    unit: "pages",
    // About the page that was submitted, for the query it targets. The page
    // projection narrows site-wide records to one page and has nothing to
    // narrow here; under any other population its site-level observation is
    // dropped and both checks come back "not tested" on every run.
    population: "target_page",
    targetTested: null,
    tested: 1,
    affected: affected ? 1 : 0,
    observations: affected
      ? [
          {
            url: null,
            values: [
              { label: "sampled_query", value: raw.keyword },
              { label: presentLabel, value: matched.join(" ") || "none" },
              { label: "serp_item_types", value: raw.itemTypes.join(" ") },
              { label: "organic_results_sampled", value: raw.organicCount },
              { label: "unresolved_serp_items", value: raw.unresolvedItemCount },
              { label: "sampled_market", value: raw.marketCode },
              { label: "sampled_language", value: raw.languageCode },
            ],
          },
        ]
      : [],
    limitation:
      raw.unresolvedItemCount > 0
        ? "some_organic_items_were_unusable_so_this_is_a_thinner_sample_than_page_one"
        : "one_live_sample_of_one_results_page_which_changes_between_requests",
  };
}

/**
 * Records for the checks about the shape of the results page (9.1, 9.4).
 *
 * Both on every run that reached this far. What they cannot do is say whether an
 * AI answer *fully* answered the query — that is a judgement about content the
 * provider does not return and this run never reads — so 9.1 is presence, and
 * its published threshold says so.
 */
export function buildSerpShapeRecords(
  raw: SerpShapeRaw | null | undefined,
  gap: SerpShapeGap = "no_confirmed_query",
): readonly SeoAuditRecord[] {
  return [
    shapeRecord(
      "ai_answer_block_present",
      raw,
      gap,
      (types) => types.filter((type) => AI_ANSWER_ITEM_TYPES.includes(type)),
      "ai_answer_item_types",
      "present",
    ),
    shapeRecord(
      "no_community_result_present",
      raw,
      gap,
      (types) => types.filter((type) => COMMUNITY_ITEM_TYPES.includes(type)),
      "community_item_types",
      "absent",
    ),
    lowTrafficRecord(raw, gap),
  ];
}

/**
 * Whether anyone on page one is small enough to be displaceable.
 *
 * The published rule reads "at least 1; otherwise lower the opportunity health
 * score", so a page one made entirely of large sites is reported as a Tip —
 * the state this product uses for "worth knowing, not a defect". It is not a
 * Warning: a hard query is not something the site did wrong.
 */
function lowTrafficRecord(
  raw: SerpShapeRaw | null | undefined,
  gap: SerpShapeGap,
): SeoAuditRecord {
  const measured = raw?.domainTraffic ?? null;
  // A domain the provider said nothing about is not a small domain. Counting
  // an unknown as low-traffic manufactures the very opening this check looks
  // for, so only domains with a number participate.
  const known = (measured ?? []).filter(
    (entry): entry is { domain: string; organicEtv: number } =>
      entry.organicEtv !== null,
  );
  if (measured === null || known.length === 0) {
    return {
      id: "page_one_without_a_low_traffic_site",
      category: "serp_shape",
      state: "unverified",
      unit: "pages",
      population: "target_page",
      targetTested: null,
      tested: 0,
      affected: 0,
      observations: [],
      limitation:
        measured === null && raw !== null && raw !== undefined
          ? "this_market_has_no_traffic_estimate_source_so_page_one_is_not_sized"
          : GAP_LIMITATION[gap],
    };
  }
  const small = known.filter(
    (entry) => entry.organicEtv < LOW_TRAFFIC_ETV_CEILING,
  );
  return {
    id: "page_one_without_a_low_traffic_site",
    category: "serp_shape",
    state: "observed",
    unit: "pages",
    population: "target_page",
    targetTested: true,
    tested: 1,
    // Affected when NOBODY on page one is small: that is the finding, and the
    // record has to carry an observation for the rule to reach it at all.
    affected: small.length === 0 ? 1 : 0,
    observations:
      small.length === 0
        ? [
            {
              url: null,
              values: [
                { label: "sampled_query", value: raw?.keyword ?? "" },
                { label: "page_one_domains_sized", value: known.length },
                {
                  label: "smallest_page_one_traffic",
                  value: Math.min(...known.map((entry) => entry.organicEtv)),
                },
              ],
            },
          ]
        : [],
    limitation: "traffic_estimates_are_modelled_not_measured_visits",
  };
}

export const SERP_SHAPE_RECORD_IDS: readonly string[] = [
  "ai_answer_block_present",
  "no_community_result_present",
  "page_one_without_a_low_traffic_site",
];

/**
 * Below this many estimated monthly organic visits, a domain reads as small
 * enough that a well-made page could displace it.
 */
export const LOW_TRAFFIC_ETV_CEILING = 1_000;

export const SERP_SHAPE_EVIDENCE_LABELS: readonly string[] = [
  "sampled_query",
  "ai_answer_item_types",
  "community_item_types",
  "serp_item_types",
  "organic_results_sampled",
  "unresolved_serp_items",
  "sampled_market",
  "sampled_language",
  "page_one_domains_sized",
  "smallest_page_one_traffic",
];

export const SERP_SHAPE_LIMITATION_CODES: readonly string[] = [
  ...Object.values(GAP_LIMITATION),
  "the_provider_reported_no_item_type_list_for_this_results_page",
  "some_organic_items_were_unusable_so_this_is_a_thinner_sample_than_page_one",
  "one_live_sample_of_one_results_page_which_changes_between_requests",
  "this_market_has_no_traffic_estimate_source_so_page_one_is_not_sized",
  "traffic_estimates_are_modelled_not_measured_visits",
];
