// @input  -- V1.3 §10.5 / §18 IssueType 闭包（45 项）+ KW 子集
// @output -- IssueType / KeywordIssueType closed enums
// @pos    -- types/ 拆分，issue 分类核心，被 CheckResult.issueType / KeywordUniverseItem.diagnostic 消费

// =====================================================
// V1.3 §10.5 / §18 IssueType 闭包（45 项）
// =====================================================

export const ALL_ISSUE_TYPES = [
  // SV1-SV8 通用 (14)
  "DATA_MISSING",
  "LOW_SAMPLE",
  "TRAFFIC_DROP",
  "IMPRESSION_DROP",
  "RANKING_DROP",
  "CTR_UNDERPERFORMANCE",
  "LOW_KEYWORD_ASSET",
  "CANNIBALIZATION",
  "PAGE_CONCENTRATION",
  "ZERO_IMPRESSION_PAGES",
  "SERP_FEATURE_GAP",
  "RICH_RESULT_ERROR",
  "COMPETITOR_GAP",
  "INTERNATIONAL_MISCONFIG",
  // SV3 / KW 专用 (30)
  "KEYWORD_DATA_INCOMPLETE",
  "KEYWORD_SOURCE_TOO_NARROW",
  "SEED_DIMENSION_GAP",
  "LOCALE_MISMATCH",
  "NONBRAND_ASSET_WEAK",
  "BRAND_DEMAND_WEAK",
  "COMPETITOR_KEYWORD_GAP",
  "CATEGORY_KEYWORD_GAP",
  "PROBLEM_USE_CASE_GAP",
  "INTENT_CLASSIFICATION_GAP",
  "FUNNEL_COVERAGE_GAP",
  "BOFU_KEYWORD_GAP",
  "ICP_JTBD_MAPPING_GAP",
  "SERP_SNAPSHOT_GAP",
  "PAGE_TYPE_MISMATCH",
  "SERP_COMPETITOR_DOMINANCE",
  "RANKING_FEASIBILITY_WEAK",
  "CLUSTERING_GAP",
  "CLUSTER_QUALITY_ISSUE",
  "HIGH_DEMAND_UNMAPPED_CLUSTER",
  "QUERY_PAGE_MAPPING_WEAK",
  "HIGH_VALUE_NO_MAPPED_PAGE",
  "KEYWORD_CANNIBALIZATION",
  "DOMINANT_URL_INSTABILITY",
  "CANONICAL_KEYWORD_CONFLICT",
  "PRIORITY_BUCKET_GAP",
  "QUICK_WIN_ASSET_EMPTY",
  "STRATEGIC_COMMERCIAL_GAP",
  "MANDATORY_KEYWORD_MISSING",
  "FORECAST_LOOP_MISSING",
  // INFO (1)
  "INFO",
] as const;
export type IssueType = (typeof ALL_ISSUE_TYPES)[number];

// V1.3 §10.3 — KW 子集，仅 KeywordUniverseItem.diagnostic.issueTypes 使用
const KEYWORD_ISSUE_TYPE_SET = [
  "KEYWORD_DATA_INCOMPLETE",
  "KEYWORD_SOURCE_TOO_NARROW",
  "SEED_DIMENSION_GAP",
  "LOCALE_MISMATCH",
  "NONBRAND_ASSET_WEAK",
  "BRAND_DEMAND_WEAK",
  "COMPETITOR_KEYWORD_GAP",
  "CATEGORY_KEYWORD_GAP",
  "PROBLEM_USE_CASE_GAP",
  "INTENT_CLASSIFICATION_GAP",
  "FUNNEL_COVERAGE_GAP",
  "BOFU_KEYWORD_GAP",
  "ICP_JTBD_MAPPING_GAP",
  "SERP_SNAPSHOT_GAP",
  "PAGE_TYPE_MISMATCH",
  "SERP_COMPETITOR_DOMINANCE",
  "RANKING_FEASIBILITY_WEAK",
  "CLUSTERING_GAP",
  "CLUSTER_QUALITY_ISSUE",
  "HIGH_DEMAND_UNMAPPED_CLUSTER",
  "QUERY_PAGE_MAPPING_WEAK",
  "HIGH_VALUE_NO_MAPPED_PAGE",
  "KEYWORD_CANNIBALIZATION",
  "DOMINANT_URL_INSTABILITY",
  "CANONICAL_KEYWORD_CONFLICT",
  "PRIORITY_BUCKET_GAP",
  "QUICK_WIN_ASSET_EMPTY",
  "STRATEGIC_COMMERCIAL_GAP",
  "MANDATORY_KEYWORD_MISSING",
  "FORECAST_LOOP_MISSING",
  "INFO",
] as const;
export const ALL_KEYWORD_ISSUE_TYPES = KEYWORD_ISSUE_TYPE_SET;
export type KeywordIssueType = (typeof KEYWORD_ISSUE_TYPE_SET)[number];
