import type {
  BriefOutlineProjectionStats,
  ContentShadowInputManifest,
  ResearchPack,
  ResearchSource,
} from "../types.ts";

/**
 * Deterministic research-pack assembly (Slice 2 Task 4).
 *
 * The pack is a pure projection of the frozen input manifest: same manifest in,
 * byte-identical pack out. It performs no retrieval — external authority
 * research and its A/B/C/D grading are Task 6 — so every source it emits is a
 * first-party SignalFrame record the customer already confirmed, and the gaps
 * are stated as explicit limitations instead of being filled with invented
 * evidence.
 */

/**
 * The fixed drafting scaffold. Determinism lives in the scaffold and the later
 * verification pass, never in generation (the ported Flow tooling works the
 * same way: it writes the prompt and gates the result, it does not invent the
 * body).
 */
export const CONTENT_SHADOW_OUTLINE: readonly string[] = [
  "Title",
  "Summary",
  "Problem",
  "Approach",
  "Evidence",
  "FAQ",
  "Sources",
  "Call To Action",
];

const NO_EXTERNAL_RESEARCH_LIMITATION =
  "This pack carries only first-party frozen SignalFrame records; no external source was retrieved or graded.";
const NO_METRIC_LIMITATION =
  "No search demand or generative citation metric was read for this run; identities are frozen without metrics.";
const QA_PENDING_LIMITATION =
  "SEO/GEO red-line, structure and citability judgement is not implemented yet; the draft requires human review.";

const BRIEF_SOURCE_LIMITATION =
  "The confirmed content brief revision is never regenerated by the shadow pipeline; its section headings, frozen cluster keywords and page-assignment decision are extracted into the draft prompt as a coverage checklist, while its prose body never enters the prompt.";

/**
 * Loud degradation (decision O-4). Extraction failure means the brief -> draft
 * causal chain is broken for this run, which is exactly the defect Task 4b
 * exists to fix. It is stated here, it forces the QA verdict off `passed`, and
 * this list is what the read API surfaces as `research.limitations`.
 */
const BRIEF_OUTLINE_UNAVAILABLE_LIMITATION =
  "Content brief outline extraction FAILED: the pinned brief revision carried no machine-readable `## ` section heading, so this draft was NOT guided by the brief. Review the draft against the brief by hand.";
const SEARCH_SOURCE_LIMITATION =
  "Search observation identity only; carries no demand volume for this run.";
const GENERATIVE_SOURCE_LIMITATION =
  "Generative observation identity only; carries no answer-sample metric for this run.";
const COMPETITOR_SOURCE_LIMITATION =
  "Competitor identity only; no competitor page was fetched or analysed for this run.";

function briefSource(manifest: ContentShadowInputManifest): ResearchSource {
  return {
    kind: "content_brief",
    ref: manifest.contentBriefArtifactId,
    authorityTier: "A",
    limitation: BRIEF_SOURCE_LIMITATION,
  };
}

/**
 * Sources are emitted in a stable order (brief, then search, then generative,
 * then competitors) over already-sorted identity sets, so the pack is stable
 * across processes and replays.
 */
function buildSources(
  manifest: ContentShadowInputManifest,
): readonly ResearchSource[] {
  return [
    briefSource(manifest),
    ...manifest.searchCluster.keywordEntityIds.map(
      (ref): ResearchSource => ({
        kind: "search_query",
        ref,
        authorityTier: "A",
        limitation: SEARCH_SOURCE_LIMITATION,
      }),
    ),
    ...manifest.generativeQueryEntityIds.map(
      (ref): ResearchSource => ({
        kind: "generative_query",
        ref,
        authorityTier: "A",
        limitation: GENERATIVE_SOURCE_LIMITATION,
      }),
    ),
    ...manifest.competitorEntityIds.map(
      (ref): ResearchSource => ({
        kind: "competitor",
        ref,
        authorityTier: "A",
        limitation: COMPETITOR_SOURCE_LIMITATION,
      }),
    ),
  ];
}

/**
 * Limitations derived from the brief-outline projection, in a fixed order so
 * the pack stays byte-stable.
 */
function briefOutlineLimitations(
  manifest: ContentShadowInputManifest,
  stats: BriefOutlineProjectionStats,
): readonly string[] {
  const limitations: string[] = [];
  if (manifest.contentBriefOutline.briefSections.length === 0) {
    limitations.push(BRIEF_OUTLINE_UNAVAILABLE_LIMITATION);
  }
  if (stats.projectedKeywordCount < stats.clusterKeywordCount) {
    limitations.push(
      `The frozen search cluster holds ${stats.clusterKeywordCount} keywords; only the first ${stats.projectedKeywordCount} (ordered by normalized keyword) were projected into the brief outline.`,
    );
  }
  if (stats.unconfirmedMappingCount > 0) {
    limitations.push(
      `${stats.unconfirmedMappingCount} of ${stats.clusterKeywordCount} frozen cluster keywords carry an unconfirmed page-mapping review state; the outline's pageAssignment therefore reflects decisions no operator has confirmed.`,
    );
  }
  return limitations;
}

/** Project one frozen manifest into its deterministic research pack. */
export function buildResearchPack(
  manifest: ContentShadowInputManifest,
  briefOutlineStats: BriefOutlineProjectionStats,
): ResearchPack {
  return {
    adapterVersion: manifest.flowAdapterVersion,
    projectionVersion: manifest.projectionVersion,
    outputLocale: manifest.outputLocale,
    brief: {
      artifactId: manifest.contentBriefArtifactId,
      revision: manifest.contentBriefRevision,
    },
    outline: [...CONTENT_SHADOW_OUTLINE],
    briefOutline: {
      briefSections: [...manifest.contentBriefOutline.briefSections],
      targetKeywords: [...manifest.contentBriefOutline.targetKeywords],
      pageAssignment: manifest.contentBriefOutline.pageAssignment,
    },
    // Two independent shapes: never a shared volume (invariant 8).
    searchObservation: {
      clusterKey: manifest.searchCluster.clusterKey,
      keywordEntityIds: [...manifest.searchCluster.keywordEntityIds],
    },
    generativeObservation: {
      generativeQueryEntityIds: [...manifest.generativeQueryEntityIds],
    },
    competitorEntityIds: [...manifest.competitorEntityIds],
    sources: buildSources(manifest),
    limitations: [
      NO_EXTERNAL_RESEARCH_LIMITATION,
      NO_METRIC_LIMITATION,
      QA_PENDING_LIMITATION,
      ...briefOutlineLimitations(manifest, briefOutlineStats),
    ],
  };
}

/** The pack as a plain JSON object for the `pack` jsonb column. */
export function researchPackToJson(
  pack: ResearchPack,
): Record<string, unknown> {
  return JSON.parse(JSON.stringify(pack)) as Record<string, unknown>;
}
