import type {
  BriefOutlineProjectionStats,
  ContentShadowCompetitorFact,
  ContentShadowContentPolicy,
  ContentShadowFirstPartyPageSnapshotIdentity,
  ContentShadowInputManifest,
  ContentShadowKeywordFact,
  ContentShadowExternalResearchTarget,
  ResearchPack,
  ResearchRetrievalSummary,
  ResearchSource,
  ResearchSourceMetrics,
  RetrievedResearchSnapshot,
} from "../types.ts";

/**
 * Deterministic research-pack assembly.
 *
 * Retrieval is intentionally outside this module. The worker freezes targets,
 * an outer adapter obtains immutable snapshot values, and this pure function
 * verifies those values against the manifest before producing a bounded pack.
 * It reads no clock, environment, filesystem, database or network.
 */

/** Fixed drafting scaffold; the model fills it, the adapter fixes it. */
export const CONTENT_SHADOW_OUTLINE: readonly string[] = [
  "Title",
  "Summary",
  "Problem",
  "Approach",
  "Evidence",
  "FAQ",
  "Sources",
  "Call To Action",
];

export const MAX_RESEARCH_SOURCE_CONTENT_CHARS = 262_144;
export const MAX_RESEARCH_PACK_CONTENT_CHARS = 1_048_576;
export const MAX_RESEARCH_SOURCE_EXCERPT_CHARS = 2_000;
export const MAX_RESEARCH_PACK_SOURCES = 1_200;

const MAX_RESEARCH_SOURCE_LABEL_CHARS = 500;
const MAX_RESEARCH_SOURCE_LIMITATION_CHARS = 2_000;
const MAX_RESEARCH_SOURCE_EVIDENCE_REFS = 100;
const MAX_RESEARCH_SOURCE_REDIRECTS = 8;

const BRIEF_SOURCE_LIMITATION =
  "The confirmed content brief revision is never regenerated by the shadow pipeline; its section headings, frozen cluster keywords and page-assignment decision are extracted into the draft prompt as a coverage checklist, while its prose body never enters the prompt.";
const SITE_ORIGIN_SOURCE_LIMITATION =
  "First-party identity only: this is the project's own site origin, frozen at accept time. It proves a link points at the customer's own property; it is not independent evidence for a claim.";
const CONVERSION_SOURCE_LIMITATION =
  "First-party identity only: this is the primary conversion target from the frozen profile. It proves where the call to action points; it is not independent evidence for a claim.";
const BRIEF_OUTLINE_UNAVAILABLE_LIMITATION =
  "Content brief outline extraction FAILED: the pinned brief revision carried no machine-readable `## ` section heading, so this draft was NOT guided by the brief. Review the draft against the brief by hand.";
const SEARCH_SOURCE_LIMITATION =
  "Frozen search keyword fact carries classifications and provenance identities, not a search-demand metric.";
const SEARCH_SOURCE_WITHOUT_EVIDENCE_LIMITATION =
  "Frozen search keyword fact has no evidence reference; its classifications are identity context, not independent support.";
const GENERATIVE_SOURCE_LIMITATION =
  "Frozen generative keyword fact carries classifications and provenance identities, not an answer-sample metric.";
const GENERATIVE_SOURCE_WITHOUT_EVIDENCE_LIMITATION =
  "Frozen generative keyword fact has no evidence reference; its classifications are identity context, not independent support.";
const COMPETITOR_SOURCE_LIMITATION =
  "Frozen competitor identity and review state only; this source does not imply that a competitor page was retrieved.";

function compareText(left: string, right: string): number {
  if (left < right) return -1;
  if (left > right) return 1;
  return 0;
}

function sortedUnique(values: readonly string[]): readonly string[] {
  return [...new Set(values.map((value) => value.trim()).filter(Boolean))].sort(
    compareText,
  );
}

function truncate(value: string, limit: number): string {
  return value.length <= limit ? value : value.slice(0, limit);
}

function nullableTrimmed(value: string | null): string | null {
  if (value === null) return null;
  const trimmed = value.trim();
  return trimmed.length === 0 ? null : trimmed;
}

/**
 * Adapter limitations are audit output, not prose for this projection to
 * normalize. Preserve them byte-for-byte and append only limitations introduced
 * by pack assembly, in a fixed causal order.
 */
function appendPackLimitations(
  adapterLimitation: string | null,
  ...packLimitations: readonly (string | null)[]
): string | null {
  const additions = packLimitations.filter(
    (limitation): limitation is string => limitation !== null,
  );
  if (additions.length === 0) return adapterLimitation;
  const appended = additions.join(" ");
  return adapterLimitation === null
    ? appended
    : `${adapterLimitation} ${appended}`;
}

function cloneMetrics(
  metrics: ResearchSourceMetrics | null,
): ResearchSourceMetrics | null {
  if (metrics === null) return null;
  return {
    status: metrics.status,
    contentType: nullableTrimmed(metrics.contentType),
    bodyBytes: metrics.bodyBytes,
    wordCount: metrics.wordCount,
    responseMs: metrics.responseMs,
    redirectChain: metrics.redirectChain
      .slice(0, MAX_RESEARCH_SOURCE_REDIRECTS)
      .map((url) => url.trim()),
  };
}

function cloneKeywordFact(fact: ContentShadowKeywordFact): ContentShadowKeywordFact {
  return {
    id: fact.id,
    display: fact.display,
    market: fact.market,
    language: fact.language,
    intent: fact.intent,
    buyerStage: fact.buyerStage,
    cluster: fact.cluster,
    mapping: {
      decision: fact.mapping.decision,
      mappedSitePageId: fact.mapping.mappedSitePageId,
      reviewState: fact.mapping.reviewState,
      revision: fact.mapping.revision,
    },
    lastSeen: fact.lastSeen,
    evidenceRefs: [...fact.evidenceRefs],
  };
}

function cloneCompetitorFact(
  fact: ContentShadowCompetitorFact,
): ContentShadowCompetitorFact {
  return {
    id: fact.id,
    domain: fact.domain,
    name: fact.name,
    status: fact.status,
    relationship: fact.relationship,
    scopes: [...fact.scopes],
    revision: fact.revision,
  };
}

function clonePolicy(
  policy: ContentShadowContentPolicy,
): ContentShadowContentPolicy {
  return {
    brandConstraints: [...policy.brandConstraints],
    complianceConstraints: [...policy.complianceConstraints],
    prohibitedTerms: [...policy.prohibitedTerms],
    claimRestrictions: [...policy.claimRestrictions],
  };
}

/** A supplied snapshot did not resolve exactly to an authorized frozen target. */
export class ResearchSnapshotIntegrityError extends Error {
  readonly code = "CONTENT_SHADOW_RESEARCH_SNAPSHOT_INTEGRITY";

  constructor(detail: string) {
    super(`research snapshot integrity check failed: ${detail}`);
    this.name = "ResearchSnapshotIntegrityError";
  }
}

function snapshotKey(snapshot: RetrievedResearchSnapshot): string {
  return `${snapshot.kind}\u0000${snapshot.ref}`;
}

function assertSnapshotCoherence(snapshot: RetrievedResearchSnapshot): void {
  if (typeof snapshot.contentTruncated !== "boolean") {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} contentTruncated must be boolean`,
    );
  }
  if (typeof snapshot.excerptTruncated !== "boolean") {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} excerptTruncated must be boolean`,
    );
  }
  if (
    snapshot.limitation !== null &&
    (snapshot.limitation.trim().length === 0 ||
      snapshot.limitation !== snapshot.limitation.trim() ||
      snapshot.limitation.length > MAX_RESEARCH_SOURCE_LIMITATION_CHARS)
  ) {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} limitation must be non-blank, unpadded and at most ${MAX_RESEARCH_SOURCE_LIMITATION_CHARS} characters`,
    );
  }
  if (
    snapshot.availability === "unavailable" &&
    snapshot.contentText !== null
  ) {
    throw new ResearchSnapshotIntegrityError(
      `unavailable ${snapshot.kind} ${snapshot.ref} supplied a content body`,
    );
  }
  if (
    (snapshot.contentHash === null) !==
    (snapshot.contentHashMethod === null)
  ) {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} must pair contentHash with contentHashMethod`,
    );
  }
  if (snapshot.contentText !== null && snapshot.contentHash === null) {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} supplied content without an auditable content hash`,
    );
  }
  if (
    snapshot.contentText !== null &&
    (snapshot.url === null ||
      snapshot.capturedAt === null ||
      snapshot.urlHash === null)
  ) {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} supplied content without terminal URL, capture time and URL hash`,
    );
  }
  if (
    snapshot.contentTruncated &&
    (snapshot.contentText === null ||
      snapshot.contentHash === null ||
      snapshot.contentHashMethod === null)
  ) {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} set contentTruncated without an auditable body and content hash`,
    );
  }
  if (
    snapshot.contentTruncated &&
    snapshot.availability !== "partial"
  ) {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} set contentTruncated but adapter availability was not partial`,
    );
  }
  if (snapshot.excerpt !== null && snapshot.contentText === null) {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} supplied an excerpt without a retained body`,
    );
  }
  if (
    snapshot.excerptTruncated &&
    (snapshot.excerpt === null || snapshot.contentText === null)
  ) {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} set excerptTruncated without an excerpt and retained body`,
    );
  }
  if (
    snapshot.excerptTruncated &&
    snapshot.excerpt !== null &&
    snapshot.contentText !== null &&
    [...snapshot.excerpt].length >= [...snapshot.contentText].length
  ) {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} set excerptTruncated but the excerpt is not shorter than the retained body`,
    );
  }
  if (snapshot.urlHash !== null && snapshot.url === null) {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} supplied a URL hash without a terminal URL`,
    );
  }
  const metrics = snapshot.metrics;
  if (metrics === null) return;
  if (
    metrics.status !== null &&
    (!Number.isSafeInteger(metrics.status) ||
      metrics.status < 100 ||
      metrics.status > 599)
  ) {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} metrics.status must be an HTTP status or null`,
    );
  }
  for (const [label, value] of [
    ["bodyBytes", metrics.bodyBytes],
    ["wordCount", metrics.wordCount],
    ["responseMs", metrics.responseMs],
  ] as const) {
    if (
      value !== null &&
      (!Number.isSafeInteger(value) || value < 0)
    ) {
      throw new ResearchSnapshotIntegrityError(
        `${snapshot.kind} ${snapshot.ref} metrics.${label} must be a non-negative safe integer or null`,
      );
    }
  }
  if (metrics.redirectChain.length > MAX_RESEARCH_SOURCE_REDIRECTS) {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} redirect chain exceeds ${MAX_RESEARCH_SOURCE_REDIRECTS} hops`,
    );
  }
  for (const redirect of metrics.redirectChain) {
    try {
      const parsed = new URL(redirect.trim());
      if (
        (parsed.protocol !== "https:" && parsed.protocol !== "http:") ||
        parsed.hostname.length === 0
      ) {
        throw new Error("not http");
      }
    } catch {
      throw new ResearchSnapshotIntegrityError(
        `${snapshot.kind} ${snapshot.ref} redirect entries must be absolute http(s) URLs`,
      );
    }
  }
}

function canonicalSnapshot(
  snapshot: RetrievedResearchSnapshot,
): RetrievedResearchSnapshot {
  assertSnapshotCoherence(snapshot);
  const evidenceRefs = sortedUnique(snapshot.evidenceRefs);
  if (evidenceRefs.length > MAX_RESEARCH_SOURCE_EVIDENCE_REFS) {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} has too many evidence references`,
    );
  }
  const normalized: RetrievedResearchSnapshot = {
    ref: snapshot.ref.trim(),
    kind: snapshot.kind,
    label: truncate(
      snapshot.label.trim(),
      MAX_RESEARCH_SOURCE_LABEL_CHARS,
    ),
    requestedUrl: snapshot.requestedUrl.trim(),
    url: nullableTrimmed(snapshot.url),
    availability: snapshot.availability,
    capturedAt: nullableTrimmed(snapshot.capturedAt),
    urlHash: nullableTrimmed(snapshot.urlHash),
    contentHash: nullableTrimmed(snapshot.contentHash),
    contentHashMethod: snapshot.contentHashMethod,
    // Preserve body bytes exactly here. Bounding happens only after snapshot
    // integrity is established, and never changes the supplied content hash.
    contentText: snapshot.contentText,
    contentTruncated: snapshot.contentTruncated,
    excerpt: snapshot.excerpt,
    excerptTruncated: snapshot.excerptTruncated,
    metrics: cloneMetrics(snapshot.metrics),
    evidenceRefs,
    limitation: snapshot.limitation,
  };
  assertSnapshotCoherence(normalized);
  return normalized;
}

function canonicalSnapshots(
  snapshots: readonly RetrievedResearchSnapshot[],
): readonly RetrievedResearchSnapshot[] {
  const normalized = snapshots.map(canonicalSnapshot);
  normalized.sort((left, right) =>
    compareText(snapshotKey(left), snapshotKey(right)),
  );
  const result: RetrievedResearchSnapshot[] = [];
  for (const snapshot of normalized) {
    const previous = result.at(-1);
    if (!previous || snapshotKey(previous) !== snapshotKey(snapshot)) {
      result.push(snapshot);
      continue;
    }
    if (JSON.stringify(previous) !== JSON.stringify(snapshot)) {
      throw new ResearchSnapshotIntegrityError(
        `conflicting values were supplied for ${snapshot.kind} ${snapshot.ref}`,
      );
    }
  }
  return result;
}

function assertEqual(
  actual: unknown,
  expected: unknown,
  detail: string,
): void {
  if (actual !== expected) {
    throw new ResearchSnapshotIntegrityError(detail);
  }
}

function assertFirstPartySnapshot(
  snapshot: RetrievedResearchSnapshot,
  frozen: ContentShadowFirstPartyPageSnapshotIdentity,
): void {
  if (
    snapshot.availability !== "available" ||
    snapshot.contentText === null
  ) {
    throw new ResearchSnapshotIntegrityError(
      `first-party PageSnapshot ${frozen.pageSnapshotId} must be supplied as an available body or omitted entirely`,
    );
  }
  assertEqual(
    snapshot.requestedUrl,
    frozen.url,
    `first-party PageSnapshot ${frozen.pageSnapshotId} requested URL drifted`,
  );
  assertEqual(
    snapshot.url,
    frozen.url,
    `first-party PageSnapshot ${frozen.pageSnapshotId} URL drifted`,
  );
  assertEqual(
    snapshot.capturedAt,
    frozen.capturedAt,
    `first-party PageSnapshot ${frozen.pageSnapshotId} capturedAt drifted`,
  );
  assertEqual(
    snapshot.urlHash,
    frozen.urlHash,
    `first-party PageSnapshot ${frozen.pageSnapshotId} URL hash drifted`,
  );
  assertEqual(
    snapshot.contentHash,
    frozen.contentHash,
    `first-party PageSnapshot ${frozen.pageSnapshotId} content hash drifted`,
  );
  assertEqual(
    snapshot.contentHashMethod,
    "sha256_canonical_extract",
    `first-party PageSnapshot ${frozen.pageSnapshotId} uses the wrong content-hash method`,
  );
}

function assertExternalSnapshot(
  snapshot: RetrievedResearchSnapshot,
  target: ContentShadowExternalResearchTarget,
): void {
  assertEqual(
    snapshot.requestedUrl,
    target.url,
    `external target ${target.ref} requested URL drifted`,
  );
  if (snapshot.availability === "available") {
    if (
      snapshot.url === null ||
      snapshot.capturedAt === null ||
      snapshot.urlHash === null ||
      snapshot.contentHash === null ||
      snapshot.contentHashMethod !== "sha256_normalized_text"
    ) {
      throw new ResearchSnapshotIntegrityError(
        `available external target ${target.ref} lacks terminal URL, capture time or reproducible hashes`,
      );
    }
  }
  if (
    snapshot.contentHash !== null &&
    snapshot.contentHashMethod !== "sha256_normalized_text"
  ) {
    throw new ResearchSnapshotIntegrityError(
      `external target ${target.ref} uses the wrong content-hash method`,
    );
  }
}

function validateAndIndexSnapshots(
  manifest: ContentShadowInputManifest,
  retrievedSnapshots: readonly RetrievedResearchSnapshot[],
): ReadonlyMap<string, RetrievedResearchSnapshot> {
  const firstParty = new Map(
    manifest.researchContext.firstPartyPageSnapshots.map((snapshot) => [
      snapshot.pageSnapshotId,
      snapshot,
    ]),
  );
  const external = new Map(
    manifest.researchContext.externalTargets.map((target) => [
      target.ref,
      target,
    ]),
  );
  const index = new Map<string, RetrievedResearchSnapshot>();
  for (const snapshot of canonicalSnapshots(retrievedSnapshots)) {
    if (snapshot.kind === "first_party_page") {
      const frozen = firstParty.get(snapshot.ref);
      if (!frozen) {
        throw new ResearchSnapshotIntegrityError(
          `first-party snapshot ${snapshot.ref} is not present in the frozen research context`,
        );
      }
      assertFirstPartySnapshot(snapshot, frozen);
    } else {
      const target = external.get(snapshot.ref);
      if (!target) {
        throw new ResearchSnapshotIntegrityError(
          `external target ${snapshot.ref} is not present in the frozen research context`,
        );
      }
      assertExternalSnapshot(snapshot, target);
    }
    index.set(snapshotKey(snapshot), snapshot);
  }
  return index;
}

function emptySource(
  fields: Pick<
    ResearchSource,
    "kind" | "ref" | "authorityTier" | "label" | "url" | "availability"
  > & {
    readonly limitation: string | null;
    readonly capturedAt?: string | null;
    readonly urlHash?: string | null;
    readonly contentHash?: string | null;
    readonly contentHashMethod?: ResearchSource["contentHashMethod"];
    readonly evidenceRefs?: readonly string[];
  },
): ResearchSource {
  return {
    kind: fields.kind,
    ref: fields.ref,
    authorityTier: fields.authorityTier,
    label: fields.label,
    url: fields.url,
    availability: fields.availability,
    capturedAt: fields.capturedAt ?? null,
    urlHash: fields.urlHash ?? null,
    contentHash: fields.contentHash ?? null,
    contentHashMethod: fields.contentHashMethod ?? null,
    contentText: null,
    contentTruncated: false,
    excerpt: null,
    excerptTruncated: false,
    metrics: null,
    evidenceRefs: [...(fields.evidenceRefs ?? [])],
    limitation: fields.limitation,
  };
}

function briefSource(manifest: ContentShadowInputManifest): ResearchSource {
  return emptySource({
    kind: "content_brief",
    ref: manifest.contentBriefArtifactId,
    authorityTier: "A",
    label: `Content brief revision ${manifest.contentBriefRevision}`,
    url: null,
    availability: "available",
    limitation: BRIEF_SOURCE_LIMITATION,
  });
}

function firstPartyIdentitySources(
  manifest: ContentShadowInputManifest,
): readonly ResearchSource[] {
  const conversionUrl = manifest.firstParty.icpPrimaryConversionUrl;
  return [
    emptySource({
      kind: "first_party_site",
      ref: manifest.firstParty.siteOrigin,
      authorityTier: "A",
      label: "First-party site",
      url: manifest.firstParty.siteOrigin,
      availability: "available",
      limitation: SITE_ORIGIN_SOURCE_LIMITATION,
    }),
    ...(conversionUrl === null
      ? []
      : [
          emptySource({
            kind: "first_party_conversion",
            ref: conversionUrl,
            authorityTier: "A",
            label: "Primary conversion target",
            url: conversionUrl,
            availability: "available",
            limitation: CONVERSION_SOURCE_LIMITATION,
          }),
        ]),
  ];
}

function keywordSources(
  facts: readonly ContentShadowKeywordFact[],
  kind: "search_query" | "generative_query",
): readonly ResearchSource[] {
  return facts.map((fact) =>
    emptySource({
      kind,
      ref: fact.id,
      authorityTier: "A",
      label: fact.display,
      url: null,
      availability: "available",
      capturedAt: fact.lastSeen,
      evidenceRefs: fact.evidenceRefs,
      limitation:
        fact.evidenceRefs.length === 0
          ? kind === "search_query"
            ? SEARCH_SOURCE_WITHOUT_EVIDENCE_LIMITATION
            : GENERATIVE_SOURCE_WITHOUT_EVIDENCE_LIMITATION
          : kind === "search_query"
            ? SEARCH_SOURCE_LIMITATION
            : GENERATIVE_SOURCE_LIMITATION,
    }),
  );
}

function competitorSources(
  facts: readonly ContentShadowCompetitorFact[],
): readonly ResearchSource[] {
  return facts.map((fact) =>
    emptySource({
      kind: "competitor",
      ref: fact.id,
      authorityTier: "A",
      label: fact.name ?? fact.domain,
      // Identity alone must not turn an unfetched domain into citable evidence.
      url: null,
      availability: "available",
      limitation: COMPETITOR_SOURCE_LIMITATION,
    }),
  );
}

interface BoundedPageSource {
  readonly source: ResearchSource;
  readonly consumedCharacters: number;
  readonly bodyTruncated: boolean;
}

function boundedPageSource(
  snapshot: RetrievedResearchSnapshot,
  fields: {
    readonly label: string;
    readonly authorityTier: ResearchSource["authorityTier"];
    readonly evidenceRefs: readonly string[];
  },
  remainingCharacters: number,
): BoundedPageSource {
  const originalText = snapshot.contentText;
  const sourceCap = Math.min(
    MAX_RESEARCH_SOURCE_CONTENT_CHARS,
    Math.max(0, remainingCharacters),
  );
  const boundedText =
    originalText === null ? null : truncate(originalText, sourceCap);
  const packContentTruncated =
    originalText !== null &&
    (boundedText?.length ?? 0) < originalText.length;
  const boundedExcerpt =
    snapshot.excerpt === null
      ? null
      : truncate(snapshot.excerpt, MAX_RESEARCH_SOURCE_EXCERPT_CHARS);
  const packExcerptTruncated =
    snapshot.excerpt !== null &&
    (boundedExcerpt?.length ?? 0) < snapshot.excerpt.length;
  const missingAvailableBody =
    snapshot.availability === "available" && originalText === null;
  const inferredAvailabilityLimitation =
    snapshot.limitation !== null
      ? null
      : snapshot.availability === "partial"
        ? "Retrieval returned only a partial page."
        : snapshot.availability === "unavailable"
          ? "Retrieval did not return an available page."
          : missingAvailableBody
            ? "Retrieval marked the page available but supplied no content body."
            : null;
  const packContentLimitation = packContentTruncated
    ? `Content text exceeded the bounded research-pack limit and was truncated to ${boundedText?.length ?? 0} characters; contentHash still identifies the complete retrieved text.`
    : null;
  const packExcerptLimitation = packExcerptTruncated
    ? `Excerpt exceeded the bounded research-pack limit and was truncated to ${MAX_RESEARCH_SOURCE_EXCERPT_CHARS} characters.`
    : null;
  const projectedAvailability =
    packContentTruncated && snapshot.availability === "available"
      ? "partial"
      : snapshot.availability;
  const evidenceRefs = sortedUnique([
    ...fields.evidenceRefs,
    ...snapshot.evidenceRefs,
  ]);
  if (evidenceRefs.length > MAX_RESEARCH_SOURCE_EVIDENCE_REFS) {
    throw new ResearchSnapshotIntegrityError(
      `${snapshot.kind} ${snapshot.ref} has too many merged evidence references`,
    );
  }
  return {
    source: {
      kind: snapshot.kind,
      ref: snapshot.ref,
      authorityTier: fields.authorityTier,
      label: fields.label,
      url: snapshot.url,
      // Adapter availability remains authoritative unless this projection
      // itself removes body content. A bounded preview alone does not make the
      // retained body partial.
      availability: projectedAvailability,
      capturedAt: snapshot.capturedAt,
      urlHash: snapshot.urlHash,
      contentHash: snapshot.contentHash,
      contentHashMethod: snapshot.contentHashMethod,
      contentText: boundedText,
      contentTruncated:
        snapshot.contentTruncated || packContentTruncated,
      excerpt: boundedExcerpt,
      excerptTruncated:
        snapshot.excerptTruncated || packExcerptTruncated,
      metrics: cloneMetrics(snapshot.metrics),
      evidenceRefs,
      limitation: appendPackLimitations(
        snapshot.limitation,
        inferredAvailabilityLimitation,
        packContentLimitation,
        packExcerptLimitation,
      ),
    },
    consumedCharacters: boundedText?.length ?? 0,
    bodyTruncated:
      snapshot.contentTruncated || packContentTruncated,
  };
}

interface PageProjection {
  readonly sources: readonly ResearchSource[];
  readonly suppliedSnapshotCount: number;
  readonly missingFirstPartyCount: number;
  readonly missingExternalCount: number;
  readonly truncatedSourceCount: number;
}

function pageSources(
  manifest: ContentShadowInputManifest,
  index: ReadonlyMap<string, RetrievedResearchSnapshot>,
): PageProjection {
  const sources: ResearchSource[] = [];
  let remainingCharacters = MAX_RESEARCH_PACK_CONTENT_CHARS;
  let suppliedSnapshotCount = 0;
  let missingFirstPartyCount = 0;
  let missingExternalCount = 0;
  let truncatedSourceCount = 0;
  const append = (bounded: BoundedPageSource): void => {
    sources.push(bounded.source);
    remainingCharacters -= bounded.consumedCharacters;
    if (bounded.bodyTruncated) truncatedSourceCount += 1;
  };

  for (const frozen of manifest.researchContext.firstPartyPageSnapshots) {
    const snapshot = index.get(`first_party_page\u0000${frozen.pageSnapshotId}`);
    const evidenceRefs = [
      `data-snapshot:${frozen.dataSnapshotId}`,
      `page-snapshot:${frozen.pageSnapshotId}`,
    ];
    if (snapshot) {
      suppliedSnapshotCount += 1;
      append(
        boundedPageSource(
          snapshot,
          {
            label: snapshot.label || frozen.url,
            authorityTier: "B",
            evidenceRefs,
          },
          remainingCharacters,
        ),
      );
      continue;
    }
    missingFirstPartyCount += 1;
    sources.push(
      emptySource({
        kind: "first_party_page",
        ref: frozen.pageSnapshotId,
        authorityTier: "B",
        label: frozen.url,
        url: frozen.url,
        availability: "partial",
        capturedAt: frozen.capturedAt,
        urlHash: frozen.urlHash,
        contentHash: frozen.contentHash,
        contentHashMethod: "sha256_canonical_extract",
        evidenceRefs,
        limitation:
          "Frozen first-party PageSnapshot identity is available, but its canonical body was not supplied to this research pack.",
      }),
    );
  }

  for (const target of manifest.researchContext.externalTargets) {
    const snapshot = index.get(`external_page\u0000${target.ref}`);
    if (snapshot) {
      suppliedSnapshotCount += 1;
      append(
        boundedPageSource(
          snapshot,
          {
            // Frozen label wins over retrieval metadata so target identity is
            // entirely determined by the hashed manifest.
            label: target.label,
            authorityTier: "B",
            evidenceRefs: [`external-target:${target.ref}`],
          },
          remainingCharacters,
        ),
      );
      continue;
    }
    missingExternalCount += 1;
    sources.push(
      emptySource({
        kind: "external_page",
        ref: target.ref,
        authorityTier: "B",
        label: target.label,
        url: target.url,
        availability: "unavailable",
        evidenceRefs: [`external-target:${target.ref}`],
        limitation:
          "No retrieved snapshot was supplied for this frozen external target.",
      }),
    );
  }

  return {
    sources,
    suppliedSnapshotCount,
    missingFirstPartyCount,
    missingExternalCount,
    truncatedSourceCount,
  };
}

function retrievalSummary(
  manifest: ContentShadowInputManifest,
  projection: PageProjection,
): ResearchRetrievalSummary {
  const sources = projection.sources;
  return {
    targetCount:
      manifest.researchContext.firstPartyPageSnapshots.length +
      manifest.researchContext.externalTargets.length,
    suppliedSnapshotCount: projection.suppliedSnapshotCount,
    availableSourceCount: sources.filter(
      (source) => source.availability === "available",
    ).length,
    partialSourceCount: sources.filter(
      (source) => source.availability === "partial",
    ).length,
    unavailableSourceCount: sources.filter(
      (source) => source.availability === "unavailable",
    ).length,
    firstPartyPageCount:
      manifest.researchContext.firstPartyPageSnapshots.length,
    externalPageCount: manifest.researchContext.externalTargets.length,
    contentSourceCount: sources.filter(
      (source) => source.contentText !== null,
    ).length,
    contentCharacterCount: sources.reduce(
      (count, source) => count + (source.contentText?.length ?? 0),
      0,
    ),
    truncatedSourceCount: projection.truncatedSourceCount,
  };
}

function plural(count: number, singular: string, pluralValue: string): string {
  return count === 1 ? singular : pluralValue;
}

function retrievalLimitations(
  manifest: ContentShadowInputManifest,
  projection: PageProjection,
  summary: ResearchRetrievalSummary,
): readonly string[] {
  const limitations: string[] = [];
  if (summary.targetCount === 0) {
    limitations.push(
      "No first-party PageSnapshot or external research target was frozen for this run.",
    );
  }
  if (manifest.researchContext.externalTargets.length === 0) {
    limitations.push(
      "No external research target was frozen in the run's actual inputs.",
    );
  }
  if (projection.missingFirstPartyCount > 0) {
    limitations.push(
      `${projection.missingFirstPartyCount} frozen first-party page ${plural(projection.missingFirstPartyCount, "snapshot body was", "snapshot bodies were")} not supplied to the pack.`,
    );
  }
  if (projection.missingExternalCount > 0) {
    limitations.push(
      `${projection.missingExternalCount} frozen external ${plural(projection.missingExternalCount, "target has", "targets have")} no retrieved snapshot.`,
    );
  }
  const suppliedPartial = projection.sources.filter(
    (source) =>
      source.availability === "partial" &&
      !source.limitation?.includes("was not supplied"),
  ).length;
  const suppliedUnavailable =
    summary.unavailableSourceCount - projection.missingExternalCount;
  if (suppliedPartial > 0) {
    limitations.push(
      `${suppliedPartial} supplied research ${plural(suppliedPartial, "snapshot is", "snapshots are")} partial; inspect its source limitation.`,
    );
  }
  if (suppliedUnavailable > 0) {
    limitations.push(
      `${suppliedUnavailable} supplied research ${plural(suppliedUnavailable, "snapshot is", "snapshots are")} unavailable; inspect its source limitation.`,
    );
  }
  if (summary.truncatedSourceCount > 0) {
    limitations.push(
      `${summary.truncatedSourceCount} research ${plural(summary.truncatedSourceCount, "source body projection was", "source body projections were")} truncated by the retrieval adapter or the pack's deterministic body-text bounds; each source retains its original audited content hash.`,
    );
  }
  return limitations;
}

function contentPolicyLimitations(
  policy: ContentShadowContentPolicy,
): readonly string[] {
  const count =
    policy.brandConstraints.length +
    policy.complianceConstraints.length +
    policy.prohibitedTerms.length +
    policy.claimRestrictions.length;
  return count === 0
    ? ["No content-policy constraint was frozen for this run."]
    : [];
}

/** Limitations derived from brief-outline projection counts. */
function briefOutlineLimitations(
  manifest: ContentShadowInputManifest,
  stats: BriefOutlineProjectionStats,
): readonly string[] {
  const limitations: string[] = [];
  if (manifest.contentBriefOutline.briefSections.length === 0) {
    limitations.push(BRIEF_OUTLINE_UNAVAILABLE_LIMITATION);
  }
  if (stats.projectedSectionCount < stats.briefSectionCount) {
    limitations.push(
      `The pinned content brief carried ${stats.briefSectionCount} distinct section headings; only the first ${stats.projectedSectionCount} (in document order) reached the draft prompt, so ${stats.briefSectionCount - stats.projectedSectionCount} committed topic(s) did not guide this draft.`,
    );
  }
  if (stats.projectedKeywordCount < stats.clusterKeywordCount) {
    limitations.push(
      `The frozen search cluster holds ${stats.clusterKeywordCount} keywords; only the first ${stats.projectedKeywordCount} (ordered by normalized keyword) were projected into the brief outline.`,
    );
  }
  if (stats.unconfirmedMappingCount > 0) {
    limitations.push(
      `${stats.unconfirmedMappingCount} of ${stats.clusterKeywordCount} frozen cluster keywords carry an unconfirmed page-mapping review state; the outline's pageAssignment therefore reflects decisions no operator has confirmed.`,
    );
  }
  return limitations;
}

/** Project one frozen manifest and already-retrieved snapshot set into a pack. */
export function buildResearchPack(
  manifest: ContentShadowInputManifest,
  briefOutlineStats: BriefOutlineProjectionStats,
  retrievedSnapshots: readonly RetrievedResearchSnapshot[],
): ResearchPack {
  const snapshotIndex = validateAndIndexSnapshots(
    manifest,
    retrievedSnapshots,
  );
  const pages = pageSources(manifest, snapshotIndex);
  const summary = retrievalSummary(manifest, pages);
  const searchFacts = manifest.researchContext.searchKeywordFacts.map(
    cloneKeywordFact,
  );
  const generativeFacts =
    manifest.researchContext.generativeKeywordFacts.map(cloneKeywordFact);
  const competitorFacts =
    manifest.researchContext.competitorFacts.map(cloneCompetitorFact);
  const sources: readonly ResearchSource[] = [
    briefSource(manifest),
    ...firstPartyIdentitySources(manifest),
    ...pages.sources.filter((source) => source.kind === "first_party_page"),
    ...keywordSources(searchFacts, "search_query"),
    ...keywordSources(generativeFacts, "generative_query"),
    ...competitorSources(competitorFacts),
    ...pages.sources.filter((source) => source.kind === "external_page"),
  ];
  if (sources.length > MAX_RESEARCH_PACK_SOURCES) {
    throw new RangeError(
      `research pack contains ${sources.length} sources (maximum ${MAX_RESEARCH_PACK_SOURCES})`,
    );
  }
  return {
    adapterVersion: manifest.flowAdapterVersion,
    projectionVersion: manifest.projectionVersion,
    outputLocale: manifest.outputLocale,
    brief: {
      artifactId: manifest.contentBriefArtifactId,
      revision: manifest.contentBriefRevision,
    },
    outline: [...CONTENT_SHADOW_OUTLINE],
    briefOutline: {
      briefSections: [...manifest.contentBriefOutline.briefSections],
      targetKeywords: [...manifest.contentBriefOutline.targetKeywords],
      pageAssignment: manifest.contentBriefOutline.pageAssignment,
    },
    searchObservation: {
      clusterKey: manifest.searchCluster.clusterKey,
      keywordEntityIds: [...manifest.searchCluster.keywordEntityIds],
      keywordFacts: searchFacts,
    },
    generativeObservation: {
      generativeQueryEntityIds: [...manifest.generativeQueryEntityIds],
      keywordFacts: generativeFacts,
    },
    competitorEntityIds: [...manifest.competitorEntityIds],
    competitorFacts,
    policy: clonePolicy(manifest.researchContext.contentPolicy),
    retrievalSummary: summary,
    sources,
    limitations: [
      ...retrievalLimitations(manifest, pages, summary),
      ...contentPolicyLimitations(manifest.researchContext.contentPolicy),
      ...briefOutlineLimitations(manifest, briefOutlineStats),
    ],
  };
}

/** The pack as a plain JSON object for the `pack` jsonb column. */
export function researchPackToJson(
  pack: ResearchPack,
): Record<string, unknown> {
  return JSON.parse(JSON.stringify(pack)) as Record<string, unknown>;
}
