import type {
  ContentShadowInputManifest,
  ResearchPack,
  ResearchSource,
} from "../types.ts";

/**
 * Deterministic research-pack assembly (Slice 2 Task 4).
 *
 * The pack is a pure projection of the frozen input manifest: same manifest in,
 * byte-identical pack out. It performs no retrieval — external authority
 * research and its A/B/C/D grading are Task 6 — so every source it emits is a
 * first-party SignalFrame record the customer already confirmed, and the gaps
 * are stated as explicit limitations instead of being filled with invented
 * evidence.
 */

/**
 * The fixed drafting scaffold. Determinism lives in the scaffold and the later
 * verification pass, never in generation (the ported Flow tooling works the
 * same way: it writes the prompt and gates the result, it does not invent the
 * body).
 */
export const CONTENT_SHADOW_OUTLINE: readonly string[] = [
  "Title",
  "Summary",
  "Problem",
  "Approach",
  "Evidence",
  "FAQ",
  "Sources",
  "Call To Action",
];

const NO_EXTERNAL_RESEARCH_LIMITATION =
  "This pack carries only first-party frozen SignalFrame records; no external source was retrieved or graded.";
const NO_METRIC_LIMITATION =
  "No search demand or generative citation metric was read for this run; identities are frozen without metrics.";
const QA_PENDING_LIMITATION =
  "SEO/GEO red-line, structure and citability judgement is not implemented yet; the draft requires human review.";

const BRIEF_SOURCE_LIMITATION =
  "The confirmed content brief revision is consumed as-is and is never regenerated by the shadow pipeline.";
const SEARCH_SOURCE_LIMITATION =
  "Search observation identity only; carries no demand volume for this run.";
const GENERATIVE_SOURCE_LIMITATION =
  "Generative observation identity only; carries no answer-sample metric for this run.";
const COMPETITOR_SOURCE_LIMITATION =
  "Competitor identity only; no competitor page was fetched or analysed for this run.";

function briefSource(manifest: ContentShadowInputManifest): ResearchSource {
  return {
    kind: "content_brief",
    ref: manifest.contentBriefArtifactId,
    authorityTier: "A",
    limitation: BRIEF_SOURCE_LIMITATION,
  };
}

/**
 * Sources are emitted in a stable order (brief, then search, then generative,
 * then competitors) over already-sorted identity sets, so the pack is stable
 * across processes and replays.
 */
function buildSources(
  manifest: ContentShadowInputManifest,
): readonly ResearchSource[] {
  return [
    briefSource(manifest),
    ...manifest.searchCluster.keywordEntityIds.map(
      (ref): ResearchSource => ({
        kind: "search_query",
        ref,
        authorityTier: "A",
        limitation: SEARCH_SOURCE_LIMITATION,
      }),
    ),
    ...manifest.generativeQueryEntityIds.map(
      (ref): ResearchSource => ({
        kind: "generative_query",
        ref,
        authorityTier: "A",
        limitation: GENERATIVE_SOURCE_LIMITATION,
      }),
    ),
    ...manifest.competitorEntityIds.map(
      (ref): ResearchSource => ({
        kind: "competitor",
        ref,
        authorityTier: "A",
        limitation: COMPETITOR_SOURCE_LIMITATION,
      }),
    ),
  ];
}

/** Project one frozen manifest into its deterministic research pack. */
export function buildResearchPack(
  manifest: ContentShadowInputManifest,
): ResearchPack {
  return {
    adapterVersion: manifest.flowAdapterVersion,
    projectionVersion: manifest.projectionVersion,
    outputLocale: manifest.outputLocale,
    brief: {
      artifactId: manifest.contentBriefArtifactId,
      revision: manifest.contentBriefRevision,
    },
    outline: [...CONTENT_SHADOW_OUTLINE],
    // Two independent shapes: never a shared volume (invariant 8).
    searchObservation: {
      clusterKey: manifest.searchCluster.clusterKey,
      keywordEntityIds: [...manifest.searchCluster.keywordEntityIds],
    },
    generativeObservation: {
      generativeQueryEntityIds: [...manifest.generativeQueryEntityIds],
    },
    competitorEntityIds: [...manifest.competitorEntityIds],
    sources: buildSources(manifest),
    limitations: [
      NO_EXTERNAL_RESEARCH_LIMITATION,
      NO_METRIC_LIMITATION,
      QA_PENDING_LIMITATION,
    ],
  };
}

/** The pack as a plain JSON object for the `pack` jsonb column. */
export function researchPackToJson(
  pack: ResearchPack,
): Record<string, unknown> {
  return JSON.parse(JSON.stringify(pack)) as Record<string, unknown>;
}
