import { buildGeoKnowledgePackV1 } from "../../lib/geo-tools/kb-knowledge-pack-contract.ts";

const AT = "2026-09-04T07:11:15.461Z";

export function geoKnowledgePackFixture() {
  const statement = (id: string, text: string) => ({ id, text, sourceRefs: ["source:home"] });
  return buildGeoKnowledgePackV1({
    schemaVersion: "marketing-geo-knowledge-pack.v1",
    meta: {
      generatedAt: AT,
      lastScanAt: AT,
      market: "US",
      language: "en",
      counts: { facts: 1, qa: 1, comparisons: 1 },
    },
    entity: {
      status: "available",
      value: {
        name: "Example Cloud",
        aliases: ["Example"],
        categories: { primary: "Workflow software", secondary: ["Team software"] },
        definitions: {
          w25: "Example Cloud is workflow software for small teams.",
          w55: "Example Cloud gives small teams a shared workflow with documented handoffs.",
          w120: "Example Cloud gives small teams a shared workflow with documented handoffs and keeps human approval in the loop.",
        },
        audience: { who: "Small operations teams", notFor: "Fully autonomous decisions" },
        founded: { year: null, team: null, location: null },
        disambiguation: "Example Cloud is the workflow product, not the similarly named consultancy.",
        links: {
          home: "https://example.com/",
          pricing: null,
          docs: "https://example.com/docs",
          about: null,
          changelog: null,
          faq: null,
        },
        sameAs: [],
        sourceRefs: ["source:home"],
      },
    },
    facts: {
      status: "available",
      value: [{
        id: "fact:approval",
        type: "feature",
        statement: "Example Cloud keeps human approval in each workflow.",
        sourceRefs: ["source:home"],
        observedAt: AT,
        nextReviewAt: null,
      }],
    },
    qa: {
      status: "partial",
      limitation: "Only questions supported by the published pages are included.",
      value: [{
        id: "qa:approval",
        intent: "trust",
        question: "Does Example Cloud replace human approval?",
        variants: ["Is approval automated?"],
        directAnswer: "No. Example Cloud keeps human approval in each workflow.",
        expansion: "Teams can document the decision while retaining a human approver.",
        sourceRefs: ["source:home"],
      }],
    },
    comparisons: {
      status: "available",
      value: [{
        id: "comparison:rival",
        competitor: { key: "rival.example", name: "Rival", confirmed: true },
        checkedAt: AT,
        rows: [{
          id: "comparison-row:approval",
          dimension: "Approval model",
          product: "Human approval remains required",
          competitor: "Configurable approval",
          sourceRefs: ["source:home", "source:rival"],
          availability: "available",
        }],
        verdict: "Both products document approvals; their approval controls differ.",
        sourceRefs: ["source:home", "source:rival"],
      }],
    },
    scope: {
      status: "available",
      value: {
        does: [statement("scope:does", "Documents workflow handoffs.")],
        doesNot: [statement("scope:not", "Does not replace human approval.")],
        needsHuman: [statement("scope:human", "A person approves each workflow.")],
        misconceptions: [statement("scope:myth", "It is workflow software, not a human team.")],
      },
    },
    evidence: {
      status: "available",
      value: {
        proof: [{
          id: "evidence:docs",
          label: "Product documentation",
          summary: "The documentation describes the human approval workflow.",
          url: "https://example.com/docs",
          sourceRefs: ["source:home"],
        }],
        changelog: [],
        press: [],
        thirdPartyProfiles: [],
      },
    },
    machine: {
      status: "available",
      value: {
        jsonLd: { status: "present", types: ["Organization"], sourceRefs: ["source:home"] },
        llms: { status: "present", sourceRefs: ["source:llms"] },
        robots: { status: "present", sourceRefs: ["source:robots"] },
        sitemap: { status: "present", urlCount: 2, knowledgePagesListed: true, sourceRefs: ["source:sitemap"] },
        hreflang: { status: "present", locales: ["en"], sourceRefs: ["source:home"] },
      },
    },
    coverage: {
      status: "available",
      value: [{
        id: "coverage:entity",
        label: "Entity definition",
        status: "partial",
        summary: "The product definition is published, but no public company history was found.",
        nextAction: "Publish an About page with company history.",
        sourceRefs: ["source:home"],
      }],
    },
    sourceCatalogue: [
      {
        id: "source:home",
        kind: "own_page",
        label: "Product page",
        url: "https://example.com/",
        competitor: null,
        availability: "available",
        reason: null,
        observedAt: AT,
        bodyHash: "a".repeat(64),
        excerpts: ["Example Cloud is workflow software. Human approval remains required."],
      },
      {
        id: "source:rival",
        kind: "competitor_page",
        label: "Rival product page",
        url: "https://rival.example/",
        competitor: { key: "rival.example", name: "Rival", confirmed: true },
        availability: "available",
        reason: null,
        observedAt: AT,
        bodyHash: "b".repeat(64),
        excerpts: ["Rival offers configurable approval."],
      },
      {
        id: "source:llms",
        kind: "llms",
        label: "llms.txt",
        url: "https://example.com/llms.txt",
        competitor: null,
        availability: "available",
        reason: null,
        observedAt: AT,
        bodyHash: "c".repeat(64),
        excerpts: ["Example Cloud product index."],
      },
      {
        id: "source:robots",
        kind: "robots",
        label: "robots.txt",
        url: "https://example.com/robots.txt",
        competitor: null,
        availability: "available",
        reason: null,
        observedAt: AT,
        bodyHash: "d".repeat(64),
        excerpts: ["User-agent: * Allow: /"],
      },
      {
        id: "source:sitemap",
        kind: "sitemap",
        label: "sitemap.xml",
        url: "https://example.com/sitemap.xml",
        competitor: null,
        availability: "available",
        reason: null,
        observedAt: AT,
        bodyHash: "e".repeat(64),
        excerpts: ["Two product URLs were observed."],
      },
    ],
  });
}
