// @input -- display locale, never source text
// @output -- explicit editor actions and honest request/review states
export const geoKbV2EditorCopy = (locale: string) => locale.toLowerCase().startsWith("zh") ? {
  input: "补充与确认", frozen: "冻结快照", save: "保存 GEO 草稿", saved: "草稿已保存", unsaved: "有未保存的修改；切换阶段不会丢弃输入。", savePending: "需要保存一次才能继续：这份草稿的存档版本与当前显示不一致，内容不会改变。",
  addRole: "添加角色", addFact: "添加事实声明", addCompetitor: "添加竞品", remove: "移除", accept: "接受此条", exclude: "排除此条", pending: "设为待审阅",
  roleLabel: "角色名称", factKey: "事实维度", editHelp: "每行一项；修改会回到待审阅，原始来源不会被改成观测事实。",
  reload: "读取已保存状态", sources: "刷新来源证据", generateRoles: "生成角色建议", prepare: "生成完整待冻结版本", busy: "正在处理…",
  saveFirst: "先保存所有 GEO 修改，再生成或刷新来源。", autosave: "草稿会在停止输入后自动保存；这个按钮立即保存。", sourceChanged: "网站档案已变化。请明确检查并采用最新完整副本，再保存。",
  reviewPending: "角色或事实仍待审阅。采用新 Profile 后须重新核对或重新生成；正文和原始引用保持不变，完成审阅并保存后才能生成完整候选。",
  staleLineage: "已保存输入或 Profile 来源版本已更新。请重新生成并明确采用角色，或移除旧来源条目；排除不会更新模型角色的来源。手工角色重新审核后可继续使用。",
  reviewCopy: "检查最新网站档案副本", dismiss: "暂不采用", adopt: "采用此建议到草稿", adoptAll: "采用全部建议到草稿", proposals: "已保存的角色建议",
  proposalHelp: "采用不会自动接受，也不会覆盖已有角色；请逐项核对并保存。", sourceHelp: "来源刷新仅返回证据；明确采用后才会更改草稿。",
  oldSource: "旧来源只保留供查看，不用于当前生成。当前可仅使用 Profile；来源刷新成功后再明确采用新证据。",
  replaceRole: "以此建议替换同 ID 角色", replaceAllRoles: "以全部建议替换当前角色组", replaceHelp: "替换按钮会明确替换当前草稿中的角色，全部回到待审阅；尚不会保存或冻结。",
  candidate: "完整待冻结版本", stale: "这个候选依据已经变化。内容保留供查阅，但不能冻结；请保存并生成新候选。",
  reviewed: "我已核对这份完整候选及其来源，并确认冻结这一版本", freeze: "冻结已审阅版本", noCandidate: "尚无完整候选。保存后生成，核对全部内容，再冻结。",
  noFrozen: "还没有冻结版本。", uncertain: "请求可能已发起，但结果尚不确定。读取已保存状态确认；不会自动再次调用模型。",
  running: "生成记录尚在处理。读取状态不会发起新的模型请求。", failed: "本次生成未完成；下方保留服务端原因和实际调用记录。",
  newInput: "使用已变更的保存输入发起新请求", newInputHelp: "上次请求可能已产生费用。此按钮针对当前已变化的输入，会发起新的调用并可能再次收费；旧请求保留可查询。",
  resendSame: "按原请求编号重发", resendHelp: "尚未读到原编号的记录，这不证明请求未执行或未计费。明确重发仍使用同一编号和同一输入，由服务端去重；不会自动重试。",
  notFoundRequest: "按原请求编号尚未读到记录，结果仍未确定。", newVersionNeeded: "相同输入的不确定记录只可查询。若要继续新工作，请修改资料并保存新版本，或明确选择已保存的新来源。", retainedRequests: "保留的旧请求（只读查询）",
  error: "操作未完成，草稿保留。", invalid: "请检查字段内容与上限；已接受事实必须有有效来源 URL 和采集时间。", conflict: "服务端草稿版本已变化。已保留输入并更新版本号，请核对后重新保存。",
  state: "状态", requestKey: "本次请求标识", readGeneration: "读取生成状态", legacy: "历史 V1 按原始内容只读展示，不补造 V2 来源。",
  recordDetails: "查看这次生成的记录标识", reason: "服务端原因", attempt: "实际发起的模型调用", recordId: "生成记录 ID",
  delivery: "响应情况", deliveries: { not_attempted: "未发起调用", response_received: "已收到响应", outcome_unknown: "结果未知" },
  model: "请求的模型", tokens: "输入 / 输出 token", requestCount: "传输层记录的请求数", billingNote: "调用数为 0 不能证明供应商没有计费。",
} : {
  input: "Supplement and confirm", frozen: "Frozen snapshot", save: "Save GEO draft", saved: "Draft saved", unsaved: "Unsaved changes are kept when switching stages.", savePending: "One save is needed before continuing: the stored draft differs from what is shown here. Its content does not change.",
  addRole: "Add role", addFact: "Add fact declaration", addCompetitor: "Add competitor", remove: "Remove", accept: "Accept item", exclude: "Exclude item", pending: "Mark pending",
  roleLabel: "Role name", factKey: "Fact dimension", editHelp: "One item per line. Edits need review again and retain their original source lineage.",
  reload: "Read saved state", sources: "Refresh source evidence", generateRoles: "Generate role proposals", prepare: "Prepare complete candidate", busy: "Working…",
  saveFirst: "Save all GEO edits before generation or source refresh.", autosave: "The draft saves itself shortly after you stop typing; this button saves immediately.", sourceChanged: "The website Profile changed. Explicitly review and adopt its complete copy, then save.",
  reviewPending: "Roles or facts still need review. A new Profile copy requires review or regeneration; text and original references are retained. Finish review and save before preparing a complete candidate.",
  staleLineage: "Saved input or the Profile source version changed. Regenerate and explicitly adopt roles, or remove old-source items; excluding a model role does not update its source. Manual roles can be reused after review.",
  reviewCopy: "Review latest Profile copy", dismiss: "Dismiss", adopt: "Adopt proposal into draft", adoptAll: "Adopt all proposals into draft", proposals: "Persisted role proposals",
  proposalHelp: "Adoption is not acceptance and does not overwrite existing roles. Review each item, then save.", sourceHelp: "Refreshing returns evidence only. Apply an item explicitly to change the draft.",
  oldSource: "This old source is kept for inspection and is not used for current generation. The current Profile can be used on its own; refresh and explicitly apply new evidence when available.",
  replaceRole: "Replace matching-ID role with this proposal", replaceAllRoles: "Replace current role group with all proposals", replaceHelp: "Replacement explicitly changes the draft roles and marks them pending. It does not save or freeze them.",
  candidate: "Complete pending version", stale: "This candidate has stale inputs. Its content is retained for inspection, but cannot be frozen. Save and prepare a new candidate.",
  reviewed: "I reviewed this complete candidate and its sources and confirm freezing this exact version", freeze: "Freeze reviewed version", noCandidate: "No complete candidate yet. Save, prepare, inspect all content, then freeze.",
  noFrozen: "No frozen version yet.", uncertain: "The request may have been dispatched, but its outcome is unknown. Read saved state to recover it; no model call is retried automatically.",
  running: "Generation is still processing. Reading its status makes no new model request.", failed: "This generation did not finish. Its server reason and actual attempt record are retained below.",
  newInput: "Start a request for the changed saved input", newInputHelp: "The earlier request may already have incurred a charge. This action uses the changed input and may incur another charge. The old request remains queryable.",
  resendSame: "Resend using the original request ID", resendHelp: "No record was found for the original ID; this does not prove it was never executed or billed. An explicit resend uses exactly the same ID and input for server deduplication. It is never automatic.",
  notFoundRequest: "No record was found for the original request ID; its outcome remains unknown.", newVersionNeeded: "An uncertain record for the same input is read-only. For new work, edit and save a new data version or explicitly select new persisted source evidence.", retainedRequests: "Retained requests (read-only recovery)",
  error: "The operation did not complete. Your draft is kept.", invalid: "Check field values and bounds. Accepted facts require a valid source URL and capture time.", conflict: "The saved draft changed. Your input is kept and its version updated; review it before saving again.",
  state: "State", requestKey: "Request identity", readGeneration: "Read generation status", legacy: "Historical V1 is displayed as stored; no V2 provenance is invented.",
  recordDetails: "Inspect this generation record", reason: "Server reason", attempt: "Model calls actually dispatched", recordId: "Generation record ID",
  delivery: "Delivery", deliveries: { not_attempted: "Not dispatched", response_received: "Response received", outcome_unknown: "Outcome unknown" },
  model: "Model requested", tokens: "Input / output tokens", requestCount: "Requests recorded by the transport", billingNote: "Zero dispatched calls is not proof that the provider did not bill.",
};
