import { NextRequest } from "next/server";
import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({
  getProjectAuditTopicModelWorkspace: vi.fn(),
}));

vi.mock("@/lib/auth/session", () => ({
  getOperatorContext: vi.fn(async () => ({
    userId: "81000000-0000-4000-8000-000000000001",
    workspaceId: "81000000-0000-4000-8000-000000000002",
  })),
}));

vi.mock("@/lib/services/growth-map-topic-model", () => ({
  getProjectAuditTopicModelWorkspace:
    mocks.getProjectAuditTopicModelWorkspace,
}));

const { GET } = await import("./route");

const projectId = "81000000-0000-4000-8000-000000000003";

function invoke(selectedProjectId = projectId) {
  return GET(
    new NextRequest(
      `http://localhost/api/mvp/projects/${selectedProjectId}/audit/topic-model`,
      { headers: { "x-request-id": "request-topic-model-workspace" } },
    ),
    { params: Promise.resolve({ projectId: selectedProjectId }) },
  );
}

beforeEach(() => {
  vi.clearAllMocks();
  mocks.getProjectAuditTopicModelWorkspace.mockResolvedValue({
    projectId,
    latestConfirmed: null,
    draft: null,
    generatedAt: "2026-07-28T00:00:00.000Z",
  });
});

describe("GET Growth Map Topic Model workspace", () => {
  it("scopes the confirmed-and-draft projection to the operator workspace", async () => {
    const response = await invoke();

    expect(response.status).toBe(200);
    expect(
      mocks.getProjectAuditTopicModelWorkspace,
    ).toHaveBeenCalledWith(
      { workspaceId: "81000000-0000-4000-8000-000000000002" },
      projectId,
    );
    await expect(response.json()).resolves.toEqual({
      data: {
        projectId,
        latestConfirmed: null,
        draft: null,
        generatedAt: "2026-07-28T00:00:00.000Z",
      },
    });
  });

  it("returns system-auto confirmation provenance without inventing an actor", async () => {
    const actorId = "81000000-0000-4000-8000-000000000001";
    const topicNodeId = "81000000-0000-4000-8000-000000000004";
    const analysisInvocationId =
      "81000000-0000-4000-8000-000000000005";
    const confirmedAt = "2026-07-28T00:00:00.000Z";
    const latestConfirmed = {
      state: "confirmed",
      projectId,
      topicModelRevision: 1,
      editRevision: 1,
      rootTopicNodeId: topicNodeId,
      nodes: [
        {
          projectId,
          topicNodeId,
          topicModelRevision: 1,
          parentTopicNodeId: null,
          label: "Customer onboarding",
          description: null,
          intentEnvelope: ["commercial"],
          lifecycleState: "active",
        },
      ],
      aliases: [],
      successorRelationships: [],
      createdAt: confirmedAt,
      createdBy: actorId,
      confirmedAt,
      confirmedBy: null,
      confirmationMode: "system_auto",
      contentHash: "a".repeat(64),
      generationSummary: {
        origin: "llm_auto_confirmed",
        generationVersion: "topic-model-generation.v1",
        baseTopicModelRevision: null,
        analysisInvocationId,
        promptSetVersion: "topic-model.prompt.v1",
        inputHash: "b".repeat(64),
        generatedAt: confirmedAt,
        keywordGroupCount: 1,
        keywordCount: 1,
        assignedCount: 1,
        unassignedGroupCount: 0,
        skippedCount: 0,
        limitations: [],
        reason: "Initial model generated by Analysis Refresh",
      },
    };
    mocks.getProjectAuditTopicModelWorkspace.mockResolvedValue({
      projectId,
      latestConfirmed,
      draft: null,
      generatedAt: confirmedAt,
    });

    const response = await invoke();

    expect(response.status).toBe(200);
    await expect(response.json()).resolves.toMatchObject({
      data: {
        latestConfirmed: {
          createdBy: actorId,
          confirmedBy: null,
          confirmationMode: "system_auto",
          generationSummary: {
            analysisInvocationId,
            assignedCount: 1,
            limitations: [],
          },
        },
      },
    });
  });

  it("rejects a malformed project identity before service access", async () => {
    const response = await invoke("customer-private-project");

    expect(response.status).toBe(404);
    await expect(response.json()).resolves.toMatchObject({
      code: "NOT_FOUND",
      status: 404,
    });
    expect(
      mocks.getProjectAuditTopicModelWorkspace,
    ).not.toHaveBeenCalled();
  });
});
